# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7be5424ddbf6b20b0e91d518c27055d02fb510da5192b547ed1c386e4d5dbfc4edd7fadfb02650779d9bf644f29fa01b40ec737002c0a1058fd56b86cc2f4cc3

test:
  secret_key_base: 4c9b850c283b3ca30eb98a5b627251dcefb0bfef1814c0a7188daf2ccdbaac0511fb34143d2831d80f0c3cda0954da99778ff96b4c1d95b733ec8881c1a5e4ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
